// <auto-generated />
using System;
using FluxoDeTrabalhoAgil.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluxoDeTrabalhoAgil.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604152959_addJsonIgnore")]
    partial class addJsonIgnore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.EntregaReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SprintReviewId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SprintReviewId");

                    b.ToTable("EntregasReview");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.MensagemDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<string>("Respostas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MensagensDaily");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.RetroCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SprintRetroId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Votos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SprintRetroId");

                    b.ToTable("RetroCards");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.Reuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResumoIA")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reunioes");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HorasDev")
                        .HasColumnType("int");

                    b.Property<string>("MetaSprint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeSprint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QtdDevs")
                        .HasColumnType("int");

                    b.Property<int>("Velocity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SprintPlannings");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintRetro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeSprint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoIA")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SprintRetros");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BugsBaixos")
                        .HasColumnType("int");

                    b.Property<int>("BugsCorrigidos")
                        .HasColumnType("int");

                    b.Property<int>("BugsCriticos")
                        .HasColumnType("int");

                    b.Property<int>("BugsEncontrados")
                        .HasColumnType("int");

                    b.Property<int>("BugsMedios")
                        .HasColumnType("int");

                    b.Property<int>("BugsPendentes")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DecisoesTomadas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EficienciaSprint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeedbackProductOwner")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeedbackScrumMaster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeSprint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParticipacaoTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Participantes")
                        .HasColumnType("int");

                    b.Property<string>("PontosMelhoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PontosPositivos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProximosPassos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StoryPointsEntregues")
                        .HasColumnType("int");

                    b.Property<int>("StoryPointsPlanejados")
                        .HasColumnType("int");

                    b.Property<int>("TasksConcluidas")
                        .HasColumnType("int");

                    b.Property<int>("TasksNaoConcluidas")
                        .HasColumnType("int");

                    b.Property<int>("TasksTotais")
                        .HasColumnType("int");

                    b.Property<string>("TaxaSucesso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TempoMedioTask")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VelocityEntregue")
                        .HasColumnType("int");

                    b.Property<int>("VelocityNaoEntregue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SprintReviews");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("NaSprint")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SprintPlanningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SprintPlanningId");

                    b.ToTable("SprintTasks");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.EntregaReview", b =>
                {
                    b.HasOne("FluxoDeTrabalhoAgil.Api.Models.SprintReview", null)
                        .WithMany("Entregas")
                        .HasForeignKey("SprintReviewId");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.RetroCard", b =>
                {
                    b.HasOne("FluxoDeTrabalhoAgil.Api.Models.SprintRetro", "SprintRetro")
                        .WithMany("Cards")
                        .HasForeignKey("SprintRetroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SprintRetro");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintTask", b =>
                {
                    b.HasOne("FluxoDeTrabalhoAgil.Api.Models.SprintPlanning", null)
                        .WithMany("Backlog")
                        .HasForeignKey("SprintPlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintPlanning", b =>
                {
                    b.Navigation("Backlog");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintRetro", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("FluxoDeTrabalhoAgil.Api.Models.SprintReview", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
